# Generated by Django 6.0.2 on 2026-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='installment_group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
