# Generated by Django 6.0.2 on 2026-02-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_payable_installment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='icon',
            field=models.CharField(default='ph-bank', max_length=60),
        ),
    ]
