# Generated by Django 6.0.2 on 2026-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bank_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payable',
            name='payment_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
