# Generated by Django 6.0.2 on 2026-02-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userdashboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payable_receipts/%Y/%m/'),
        ),
    ]
