# Generated by Django 6.0.2 on 2026-02-20 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner_fields(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Bank = apps.get_model("dashboard", "Bank")
    Transaction = apps.get_model("dashboard", "Transaction")
    Payable = apps.get_model("dashboard", "Payable")

    default_user = User.objects.order_by("id").first()
    if not default_user:
        return

    for bank in Bank.objects.filter(owner__isnull=True):
        bank.owner_id = default_user.id
        bank.save(update_fields=["owner"])

    for tx in Transaction.objects.filter(owner__isnull=True):
        tx.owner_id = tx.bank.owner_id if tx.bank_id and tx.bank and tx.bank.owner_id else default_user.id
        tx.save(update_fields=["owner"])

    for payable in Payable.objects.filter(owner__isnull=True):
        payable.owner_id = (
            payable.bank.owner_id if payable.bank_id and payable.bank and payable.bank.owner_id else default_user.id
        )
        payable.save(update_fields=["owner"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_payable_payment_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], max_length=12)),
                ('new_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], max_length=12)),
                ('previous_payment_date', models.DateField(blank=True, null=True)),
                ('new_payment_date', models.DateField(blank=True, null=True)),
                ('previous_payment_note', models.CharField(blank=True, default='', max_length=255)),
                ('new_payment_note', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payable',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='bank',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.RunPython(backfill_owner_fields, noop_reverse),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_bank_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_bank_slug_per_owner'),
        ),
        migrations.AddField(
            model_name='payablestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payablestatushistory',
            name='payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='dashboard.payable'),
        ),
    ]
