# Generated by Django 6.0.2 on 2026-02-21 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_payablestatushistory_bank_owner_payable_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('color', models.CharField(default='#5D7084', max_length=7)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payable_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='dashboard.payablecategory'),
        ),
        migrations.AddConstraint(
            model_name='payablecategory',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_payable_category_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='payablecategory',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_payable_category_slug_per_owner'),
        ),
    ]
