# Generated by Django 6.0.2 on 2026-02-21 04:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_payablecategory_payable_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('creator_name', models.CharField(blank=True, default='', max_length=120)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluido'), ('canceled', 'Cancelado')], default='pending', max_length=12)),
                ('importance', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=12)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('all_day', models.BooleanField(default=False)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
    ]
